"""add student data model

Revision ID: aadd2872f2e6
Revises: fde3cb2aa55a
Create Date: 2022-03-18 14:25:07.385701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadd2872f2e6'
down_revision = 'fde3cb2aa55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sure_name', sa.Text(), nullable=False),
    sa.Column('theme_NKR', sa.Text(), nullable=False),
    sa.Column('supervisor', sa.Text(), nullable=False),
    sa.Column('NK_pages', sa.Integer(), nullable=False),
    sa.Column('NKR_pages', sa.Integer(), nullable=False),
    sa.Column('slides_pages', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('specialize', sa.Text(), nullable=False),
    sa.Column('type_education', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_data')
    # ### end Alembic commands ###
